### ISSUE TITLE
Failed to activate the advanced-open-file package

### ISSUE THREAD

**Issue by Minoost** [Osmose/advanced-open-file#104]
[Enter steps to reproduce below:]

1. Press ```Ctrl+ALT+O``` or Ctrl+Shift+P then```Advanced Open File: Toggle```

**Atom Version**: 1.7.1
**System**: Windows 10 Pro (Korean)
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.15.0

### Stack Trace

Failed to activate the advanced-open-file package

```
At inst.render is not a function

TypeError: inst.render is not a function
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:607:32)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:220:30)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:591:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:479:29)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:225:34)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:591:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:479:29)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:225:34)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:591:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:479:29)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:225:34)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:225:34)
    at Object.ReactReconciler.mountComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:37:35)
    at mountComponentIntoNode (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:266:32)
    at ReactReconcileTransaction.Mixin.perform (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\Transaction.js:136:20)
    at batchedMountComponentIntoNode (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:282:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactUpdates.js:94:20)
    at Object.ReactMount._renderNewRootComponent (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:476:18)
    at Object.ReactMount._renderSubtreeIntoContainer (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:550:32)
    at Object.ReactMount.render (C:\Users\Mino\.atom\packages\go-debug\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:570:23)
    at new AdvancedOpenFileView (C:/Users/Mino/.atom/packages/advanced-open-file/lib/view.js:24:33)
    at new AdvancedOpenFileController (C:/Users/Mino/.atom/packages/advanced-open-file/lib/controller.js:24:21)
    at Object.activate (C:/Users/Mino/.atom/packages/advanced-open-file/lib/advanced-open-file.js:11:18)
    at Package.module.exports.Package.activateNow (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package.js:183:20)
    at C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Mino\AppData\Local\atom\app-1.7.1\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:07.0 core:page-up (div.package-detail.panels-item)
     -0:01.5.0 advanced-open-file:toggle (div.panels)
```

### Config

```json
{
  "core": {},
  "advanced-open-file": {
    "createDirectories": true,
    "fuzzyMatch": true,
    "helmDirSwitch": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.15.0
atom-alignment, v0.12.1
atom-yeoman, v0.3.15
autocomplete-go, v1.0.6
builder-go, v1.0.0
environment, v1.2.0
file-icons, v1.7.4
go-config, v1.1.4
go-debug, v0.1.7
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-selected, v0.11.2
indent-guide-improved, v1.4.5
json-schema, v0.1.15
linter, v1.11.4
minimap, v4.22.1
minimap-cursorline, v0.1.0
navigator-godef, v1.0.2
omnisharp-atom, v0.28.0
project-plus, v0.8.2
rest-client, v1.0.0
sync-settings, v0.7.2
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by Osmose** [comment]
Thanks for the report!

I think this is due to https://github.com/jgebhardt/react-for-atom/issues/10. I'm going to revert 0.15.0 and then look into this.

**Comment by Osmose** [comment]
Let's just use #103 for tracking react-for-atom issues.

**Comment by immuzov** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.16.2


### Stack Trace

Failed to activate the advanced-open-file package

```
At Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/node_modules/fbjs/lib/invariant.js:34:15)
    at Object.ReactOwner.addComponentAsRefTo (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactOwner.js:67:373)
    at attachRef (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactRef.js:23:16)
    at Object.ReactRef.attachRefs (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactRef.js:42:5)
    at ReactDOMComponent.attachRefs (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactReconciler.js:22:12)
    at CallbackQueue._assign.notifyAll (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/CallbackQueue.js:66:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactReconcileTransaction.js:79:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/Transaction.js:149:16)
    at batchedMountComponentIntoNode (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:124:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactUpdates.js:97:20)
    at Object.ReactMount._renderNewRootComponent (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:277:18)
    at Object.ReactMount._renderSubtreeIntoContainer (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:354:32)
    at Object.ReactMount.render (/Users/immuzov/.atom/packages/advanced-open-file/node_modules/react/lib/ReactMount.js:374:23)
    at new AdvancedOpenFileView (/Users/immuzov/.atom/packages/advanced-open-file/lib/view.js:23:33)
    at new AdvancedOpenFileController (/Users/immuzov/.atom/packages/advanced-open-file/lib/controller.js:23:21)
    at Object.activate (/Users/immuzov/.atom/packages/advanced-open-file/lib/advanced-open-file.js:11:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -1:11.2.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:10.8.0 editor:move-line-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:10 editor:move-line-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:09.8.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:09.6.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:09.2.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:08.9.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:31.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:29.1.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:18.8.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:04.6.0 remote-edit:show-open-files (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 advanced-open-file:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "mantrajs",
      "Stylus",
      "language-ejs",
      "open-on-bitbucket",
      "pinned-tabs",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-javascript",
      "language-java",
      "language-go",
      "language-csharp",
      "language-clojure",
      "language-c",
      "jscs-fixer",
      "minimap-bookmarks",
      "bookmarks",
      "minimap",
      "atom-storybook",
      "activate-power-mode",
      "linter-jscs",
      "unregistered",
      "atom-sync"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
advanced-open-file, v0.16.2
atom-beautify, v0.29.7
atom-jade, v0.3.0
change-case, v0.6.0
docblockr, v0.7.3
easy-motion-redux, v1.1.0
editorconfig, v1.4.1
emmet, v2.4.3
file-icons, v1.7.11
filesize, v0.4.2
hyperclick, v0.0.36
indent-guide-improved, v1.4.8
js-hyperclick, v1.4.2
language-babel, v2.20.10
language-postcss, v1.2.0
linter, v1.11.4
linter-eslint, v7.2.2
merge-conflicts, v1.4.2
oceanic-next, v0.1.2
pigments, v0.26.3
project-manager, v2.9.7
relative-numbers, v0.5.1
remote-edit, v1.8.24
tidy-tabs, v0.3.0
vim-mode, v0.65.0
wordpress-api, v1.2.2

# Dev
No dev packages
```
