### ISSUE TITLE
Uncaught TypeError: Array.prototype.indexOf called on null or undefined

### ISSUE THREAD

**Issue by samuelsantoso** [Osmose/advanced-open-file#110]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.16.2

### Stack Trace

Uncaught TypeError: Array.prototype.indexOf called on null or undefined

```
At /C:/Users/samue/.atom/packages/css-spy/lib/css-spy.coffee:104

TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (native)
    at file:///C:/Users/samue/.atom/packages/css-spy/lib/css-spy.coffee:68:18
    at file:///C:/Users/samue/.atom/packages/css-spy/lib/css-spy.coffee:51:13
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\samue\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\samue\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\samue\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1378:25
```

### Commands

```
     -1:12.9.0 core:save-as (atom-text-editor.editor.is-focused)
  3x -1:05.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:01.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "advanced-open-file": {
    "createDirectories": true,
    "createFileInstantly": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
css-spy, v0.5.1
file-icons, v1.7.8
language-blade, v0.25.2
laravel, v0.7.0
minimap, v4.23.2
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by ripter** [comment]
Looks like your issue is with `css-spy` and not `advanced-open-file`. You should try to file a bug with them. https://github.com/stackroute/atom-css-spy/issues

**Comment by Osmose** [comment]
Oh, good catch! @ripter is right, I think. Actually, I don't see advanced-open-file in the list of packages at all, how did it get attributed to this? Weird.
