### ISSUE TITLE
Uncaught Error: EACCES: permission denied, mkdir '/atom:'

### ISSUE THREAD

**Issue by kwpeng** [Osmose/advanced-open-file#89]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.14.1

### Stack Trace

Uncaught Error: EACCES: permission denied, mkdir '/atom:'

```
At /Users/kdpeng/.atom/packages/advanced-open-file/lib/models.js:121

Error: EACCES: permission denied, mkdir '/atom:'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at sync (/opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/output-file-sync/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/output-file-sync/node_modules/mkdirp/index.js:77:24)
    at Path.createDirectories (/Users/kdpeng/.atom/packages/advanced-open-file/lib/models.js:118:20)
    at AdvancedOpenFileController.openPath (/Users/kdpeng/.atom/packages/advanced-open-file/lib/controller.js:126:18)
    at AdvancedOpenFileController.selectPath (/Users/kdpeng/.atom/packages/advanced-open-file/lib/controller.js:98:18)
    at AdvancedOpenFileController.confirm (/Users/kdpeng/.atom/packages/advanced-open-file/lib/controller.js:219:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.3.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:57.3.0 settings-view:open (div.panels-item)
     -1:26.6.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
  3x -1:25.2.0 core:backspace (atom-text-editor.path-input.editor.mini.is-focused)
     -1:22.5.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
     -0:08.7.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "advanced-open-file": {
    "createFileInstantly": true,
    "defaultInputValue": "Empty"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.1
file-icons, v1.6.13
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by Osmose** [comment]
Thanks for the report! I'll try to replicate this soon, hopefully sometime this weekend.

**Comment by Osmose** [comment]
I have a pull request up that adds some nice error messaging when attempting to create files or directories fails, such as permission errors such as this one: https://github.com/Osmose/advanced-open-file/pull/90

Would you be willing to test out the branch to see if it fixes your issue? The README has instructions on how to set up and test a dev instance of the package easily.

**Comment by Osmose** [comment]
Calling this fixed. Feel free to reopen if I'm wrong. Thanks again!
