### ISSUE TITLE
Failed to activate the advanced-open-file package

### ISSUE THREAD

**Issue by keviswang** [Osmose/advanced-open-file#98]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.14.3

### Stack Trace

Failed to activate the advanced-open-file package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/keviswang/.atom/packages/advanced-open-file/lib/controller.js:5:41)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/keviswang/.atom/packages/advanced-open-file/lib/advanced-open-file.js:9:19)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  4x -1:00.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:40.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.0 advanced-open-file:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-perl",
      "language-ruby-on-rails",
      "exception-reporting",
      "language-clojure",
      "language-toml",
      "language-mustache",
      "about",
      "archive-view",
      "language-c",
      "linter-jscs"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": false,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "advanced-open-file": {
    "createFileInstantly": true,
    "helmDirSwitch": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.3
atom-autocomplete-php, v0.18.7
auto-detect-indentation, v1.0.0
highlight-line, v0.11.1
highlight-selected, v0.11.2
jsformat, v0.9.3
language-elixir, v0.12.3
language-vue, v0.9.0
linter, v1.11.3
project-manager, v2.7.6
react, v0.14.1
seti-syntax, v0.4.1
seti-ui, v0.9.1
sync-settings, v0.7.0
tabs-to-spaces, v1.0.2
todo-show, vundefined

# Dev
No dev packages
```

**Comment by Osmose** [comment]
Thanks for the report!

That's really odd, we require `event-kit` as a dependency (https://github.com/Osmose/advanced-open-file/blob/master/package.json#L35) and it's never failed before. Are you able to replicate this after removing and reinstalling the package?

If not, are you doing anything besides just attempting to activate the package to cause the issue?

**Comment by keviswang** [comment]
@Osmose Everything is ok after reinstalling the package. But this is really werid.

**Comment by Osmose** [comment]
Huh. Well, I'm glad it's working. If anyone else reports this then I'll look into it more.

**Comment by Osmose** [comment]
Renaming this so that the atom error dialog doesn't keep flagging it for _any_ error upon package activation.
